spring:
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false"
    hikari:
      connectionTimeout: 5000
      maximumPoolSize: 5

spring.jpa.open-in-view: true

logging.level.org.springframework.transaction: WARN
logging.level.com.zaxxer.hikari: WARN